// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UeharaApi_91Tel.EntityFramework;

namespace UeharaApi_91Tel.Migrations
{
    [DbContext(typeof(LogResponseDbContext))]
    partial class LogResponseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UeharaApi_91Tel.Models.LogResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArquivoFonte");

                    b.Property<string>("Contexto");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Excecao");

                    b.Property<int?>("LinhaFonte");

                    b.Property<int?>("LogContextoId");

                    b.Property<int?>("LogSistemaId");

                    b.Property<string>("Maquina");

                    b.Property<string>("Mensagem");

                    b.Property<string>("MetodoFonte");

                    b.Property<string>("NomeUsuario");

                    b.Property<string>("Origem");

                    b.Property<int?>("OrigemId");

                    b.Property<string>("Propriedades");

                    b.Property<string>("Severidade");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("LogModel");
                });
#pragma warning restore 612, 618
        }
    }
}
